### ISSUE TITLE
Does this scrape even the sublinks?

### ISSUE THREAD

**Issue by saiaprameya** [techwithtim/AI-Web-Scraper#1]
Hi Tim,

This is not an issue as such. Just wanted to know if it scrapes further recursively on the links present in the page ?

Regards
Sai

**Comment by BrianMosbeux** [comment]
Hi Sai,

It does not. 

You could just use beautifulsoup to find the links present on the page and then run the scrape_website function on these links.
```python
def extract_links(html_content):
    soup = BeautifulSoup(html_content, "html.parser")
    url_list = soup.find_all('a', href=True)
    return url_list

link_list = extract_urls
for l in links:
    scrape_website(l)
``` 
You will probably want to put some condition before scraping the lin...

Hope this help

**Comment by saiaprameya** [comment]
Thanks Brian for the info. Will chk this out.
